#!/bin/sh -eux

cd $UB_OBJECTDIR

export LD_LIBRARY_PATH="$(pwd)"/lib

$UB_COMPILEDIR/configure \
	-platform linux-g++-64 \
	-prefix /usr/lib/qt6 \
	-sysconfdir /etc/xdg \
	\
	-cmake              \
	-release            \
	-opensource         \
	-confirm-license	\
	-shared             \
	-journald			\
	-ccache             \
	-no-pch             \
	-qml-debug			\
	-no-use-gold-linker \
	-reduce-relocations \
	-no-rpath           \
	\
	-nomake examples    \
	-nomake tests		\
	\
	-accessibility      \
	\
	-plugin-sql-sqlite  \
	\
	-system-freetype	\
	-system-harfbuzz	\
	-system-libjpeg     \
	-system-libpng      \
	-system-pcre		\
	-system-sqlite		\
	-system-zlib        \
	\
	-dbus-linked        \
	-openssl-linked     \
	-ssl               \
	\
	-cups               \
	-glib               \
	-gtk				\
	-opengl             \
	-no-linuxfb         \
	-no-eglfs           \
	-no-kms             \
	-no-libproxy		\
	\
	-fontconfig         \
	-evdev				\
	-mtdev				\
	-libinput			\
	-tslib              \
#	\
#	-system-webengine-icu \
#	-system-ffmpeg

j="-j${UB_MAKE_PROCS:-$(_procs)}"
ninja "$j"
