#!/bin/sh -eux

cd $UB_OBJECTDIR

DESTDIR="$UB_INSTALLDIR" ninja install

# Drop QMAKE_PRL_BUILD_DIR because reference the build dir
find "$UB_INSTALLDIR/usr/lib" -type f -name '*.prl' \
	-exec sed -i -e '/^QMAKE_PRL_BUILD_DIR/d' {} \;

# a desktop fájlok kedvéért szimlinkelünk az /usr/bin-be

ln -s ../lib/qt6/bin/assistant "$UB_INSTALLDIR"/usr/bin/assistant-qt6
ln -s ../lib/qt6/bin/designer "$UB_INSTALLDIR"/usr/bin/designer-qt6
ln -s ../lib/qt6/bin/linguist "$UB_INSTALLDIR"/usr/bin/linguist-qt6
ln -s ../lib/qt6/bin/qdbusviewer "$UB_INSTALLDIR"/usr/bin/qdbusviewer-qt6

# ikonok a desktop fájlokhoz
install -Dm644 $UB_COMPILEDIR/qttools/src/assistant/assistant/images/assistant-128.png \
                  "$UB_INSTALLDIR"/usr/share/pixmaps/assistant-qt6.png
install -Dm644 $UB_COMPILEDIR/qttools/src/designer/src/designer/images/designer.png \
                  "$UB_INSTALLDIR"/usr/share/pixmaps/designer-qt6.png
install -Dm644 $UB_COMPILEDIR/qttools/src/linguist/linguist/images/icons/linguist-128-32.png \
                  "$UB_INSTALLDIR"/usr/share/pixmaps/linguist-qt6.png
install -Dm644 $UB_COMPILEDIR/qttools/src/qdbus/qdbusviewer/images/qdbusviewer-128.png \
                  "$UB_INSTALLDIR"/usr/share/pixmaps/qdbusviewer-qt6.png

ln -s ../lib/qt6/bin/qmake "$UB_INSTALLDIR"/usr/bin/qmake-qt6
ln -s ../lib/qt6/libexec/moc "$UB_INSTALLDIR"/usr/bin/moc-qt6
ln -s ../lib/qt6/libexec/rcc "$UB_INSTALLDIR"/usr/bin/rcc-qt6
ln -s ../lib/qt6/libexec/uic "$UB_INSTALLDIR"/usr/bin/uic-qt6
