#!/bin/sh -e

query_immodules ()
{
	[ -z "${UHU_PKG_QUIET+x}" ] && echo -n "  Querying GTK3 input methods ..."
	touch /usr/lib/gtk-4.0/4.0.0/immodules.cache
	gtk4-query-immodules --update-cache
	true > /var/lib/uhu-pkg/gtk-immodules
	while [ ! /var/lib/uhu-pkg/gtk4-immodules -ot /var/lib/dpkg/info \
	     -a ! /var/lib/uhu-pkg/gtk4-immodules -nt /var/lib/dpkg/info ]; do
		sleep 0.1
		true > /var/lib/uhu-pkg/gtk4-immodules
	done
	[ -z "${UHU_PKG_QUIET+x}" ] && echo
}

if [ "$2" = "upgrade" ]; then
	exit 0
fi

if [ ! -f /var/lib/uhu-pkg/gtk4-immodules ]; then
	query_immodules
fi
